### ISSUE TITLE
The Commons Name update - Internationally Regulated Digital Transparency and Consent Commons (IRDTCC)

### ISSUE THREAD

**Issue by smartopian** [GPR-NGO/0PN-Code#7]
### Discussed in https://github.com/GPR-NGO/0PN-Code/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **smartopian** August  1, 2023</sup>
A request to formally define it has come in, by the project admin.  So we are going to action this now, but leave this discussion open for comments and ideas, in case there are any good reasons to reverse this decision comes up,   As a way to start the consensus protocol. 

</div>

**Comment by smartopian** [comment]
@GigiAgassini - please update the name -

**Comment by smartopian** [comment]
Hi @GigiAgassini is it true - you are the project admin and only have read access rights?

**Comment by smartopian** [comment]
you now have admin access on this - i think in order make changes as the maintainer, you would of needed to clone the repo - make the changes - and then push them back - decentralized version of doing the task -

**Comment by smartopian** [comment]
pls try to update the doc and title now and let me know how it goes

**Comment by GigiAgassini** [comment]
i will try again and tell you

**Comment by GigiAgassini** [comment]
it is done, the document with the changes we discussed is now update in the github. Thank you for the access
